name: build
run-name: ${{ github.event.head_commit.message }}
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npm ci --silent
      - run: npm run compile
